import { Check, FileCode2, Plus, Search, Sparkles, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

import { StatusBadge } from "../components/StatusBadge";
import { EvidenceBlock } from "../components/EvidenceBlock";
import type { ApiClient, SkillDocument } from "../lib/api";

export function SkillsPage({ api }: { api: ApiClient }) {
  const [items, setItems] = useState<SkillDocument[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [query, setQuery] = useState(""); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [proposing, setProposing] = useState(false); const [proposalNote, setProposalNote] = useState<string>();
  const load = useCallback(async () => { try { setLoading(true); const next = await api.listSkills(); setItems(next); setSelectedId((current) => current && next.some((item) => item.id === current) ? current : next[0]?.id); setError(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : "加载失败"); } finally { setLoading(false); } }, [api]);
  useEffect(() => { void load(); }, [load]);
  // 人工触发 Skill 提案：模型从最近证据提取可执行工作流，只产出 Draft
  const runProposal = async () => { try { setProposing(true); setProposalNote(undefined); const report = await api.runSkillProposal(); const rejectedNote = report.rejected.length > 0 ? `；拒绝 ${report.rejected.length} 条候选（占位、格式或缺少来源）` : ""; setProposalNote(`已生成 ${report.created.length} 条草稿${rejectedNote} · 模型 ${report.model || "未调用"} · ${report.latencyMs}ms`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "提案生成失败"); } finally { setProposing(false); } };
  const filtered = useMemo(() => items.filter((item) => `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [items, query]); const selected = items.find((item) => item.id === selectedId);
  return <section className="workspace"><header className="page-head"><div><p className="eyebrow">SKILL / EXECUTABLE KNOWLEDGE</p><h1>Skill 库</h1><p>管理可复用的执行方法、版本与审核状态。</p></div><div className="page-actions"><button className="secondary" onClick={() => void runProposal()} disabled={proposing}><Sparkles size={17} />{proposing ? "生成中…" : "从证据生成草稿"}</button><button className="primary" onClick={() => setCreating(true)}><Plus size={17} />新建 Skill</button></div></header>{proposalNote && <div className="info-banner">{proposalNote}</div>}{error && <div className="error-banner">{error}</div>}<div className="split-panel"><aside className="asset-list"><label className="search"><Search size={16} /><input aria-label="搜索 Skill" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索名称或描述" /></label><div className="list-meta"><span>{filtered.length} 个 Skill</span><span>按更新时间</span></div><div className="list-scroll">{loading && <Empty text="正在加载 Skill…" />}{!loading && filtered.length === 0 && <Empty text="还没有 Skill，先创建一份可执行方法。" />}{filtered.map((item) => <button key={item.id} className={`asset-row ${selectedId === item.id ? "is-active" : ""}`} onClick={() => setSelectedId(item.id)}><div className="asset-row-top"><span className="layer">V{item.version}</span><StatusBadge status={item.status} /></div><strong className="skill-name">{item.name}</strong><p>{item.description}</p><small>{formatDate(item.updatedAt)}</small></button>)}</div></aside><main className="detail-pane">{selected ? <SkillDetail item={selected} api={api} onTransition={async (target) => { try { await api.transitionSkill(selected.id, target); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "状态更新失败"); } }} /> : <Empty text="选择一个 Skill 查看 SKILL.md" />}</main></div>{creating && <SkillDialog onClose={() => setCreating(false)} onSubmit={async (input) => { await api.createSkill(input); setCreating(false); await load(); }} />}</section>;
}

function SkillDetail({ item, api, onTransition }: { item: SkillDocument; api: ApiClient; onTransition: (target: "verified" | "rejected" | "archived") => Promise<void> }) { return <div className="detail-content"><div className="detail-title"><div><span className="mono-id">SKILL.md · VERSION {item.version}</span><h2 className="skill-heading">{item.name}</h2><p>{item.description}</p></div><StatusBadge status={item.status} /></div><pre className="code-document">{item.content}</pre><div className="note"><span>来源证据（审核时对照原文）</span><EvidenceBlock api={api} evidenceIds={item.sources.map((source) => source.evidenceId)} /></div><div className="detail-actions">{item.status === "draft" && <><button className="primary" onClick={() => void onTransition("verified")}><Check size={16} />验证通过</button><button className="danger" onClick={() => void onTransition("rejected")}><X size={16} />拒绝</button></>}{(item.status === "verified" || item.status === "deprecated") && <button className="secondary" onClick={() => void onTransition("archived")}>归档</button>}</div></div>; }

function SkillDialog({ onClose, onSubmit }: { onClose: () => void; onSubmit: (input: { name: string; description: string }) => Promise<void> }) { const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false); const [submitError, setSubmitError] = useState<string>(); return <div className="modal-backdrop" role="presentation"><form className="modal" onSubmit={(event) => { event.preventDefault(); setSaving(true); setSubmitError(undefined); void onSubmit({ name, description }).catch((reason) => setSubmitError(reason instanceof Error ? reason.message : "Skill 创建失败")).finally(() => setSaving(false)); }}><div className="modal-head"><div><p className="eyebrow">NEW SKILL</p><h2>创建 Skill 草稿</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="关闭"><X /></button></div><label>名称<input aria-label="名称" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={name} onChange={(e) => setName(e.target.value)} placeholder="review-code" /><small>使用小写字母、数字和连字符</small></label><label>描述<textarea aria-label="描述" required value={description} onChange={(e) => setDescription(e.target.value)} placeholder="一句话说明它解决什么问题" /></label>{submitError && <div className="login-error">{submitError}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>取消</button><button className="primary" disabled={saving}>{saving ? "创建中…" : "创建草稿"}</button></div></form></div>; }

function Empty({ text }: { text: string }) { return <div className="empty"><FileCode2 /><p>{text}</p></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
